# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a10799d75a9eb7463db7fe574b0533f8155fa2db57918c2cc682bc573ac587d841066862655ef3eb33bcd342f84d612856630423c1276fa0974ae9a89f36646

test:
  secret_key_base: d3332e3e47654377d026a51cbd9930d4368d52b8aaefa9c3eea55d47ba9d0a342407f675623062fe675ef5106e973e4d2b2257a2ebc54b162f8f614df1435597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
